- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.common/src/main/java/org/wso2/carbon/identity/api/user/challenge/common/Constant.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/core/UserChallengeService.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/core/functions/ChallengeQuestionToExternal.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/core/functions/UserChallengeAnswerToExternal.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Constants.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Util.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/error/APIError.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/error/ErrorDTO.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/error/ErrorResponse.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UserIdToUser.java
> Add code comments

- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/UserIdApi.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/UserIdApiService.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/resources/authorizedApps.yaml
> Refactor authorized apps API
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Refactor authorized apps API

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/AssociationEndpointConstants.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/util/Utils.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
> Adding class level java comments.
> Adding class level java comments.

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/core/AuthorizedAppsService.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/core/Constants.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/core/functions/OAuthConsumerAppToExternal.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.common/src/main/java/org/wso2/carbon/identity/api/user/challenge/common/Constant.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/core/UserChallengeService.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/core/functions/ChallengeQuestionToExternal.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/core/functions/UserChallengeAnswerToExternal.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/error/ErrorDTO.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/error/ErrorResponse.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UserIdToUser.java
- pom.xml
> Upgrade wso2 parent pom version to v5 …
> Upgrade wso2 parent pom version to v5

- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/UserIdApi.java
> Fix Autowire issue
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable …
> Fix Autowire issue

- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.api.user.approval.common/pom.xml
- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/pom.xml
- pom.xml
> Update parent pom path in approval modules

- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/UserIdApi.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/resources/challenge.yaml
- Update challenge question management swagger definition with the correct status codes
> Update status code in challenge.yaml

- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/approval/v1/core/UserApprovalService.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/UserIdApi.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/resources/challenge.yaml
> Add 403 to challenges v1 swagger

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/UserIdApi.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/UserIdApiService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/AssociationRequestDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/AssociationSwitchRequestDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/AssociationUserRequestDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/ErrorDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/PropertyDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/UserDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
> Modify swagger definition.

- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/fido2/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.v1/src/main/resources/META-INF/cxf/user-fido2-v1-cxf.xml
> Fix fido2 Autowired issue
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Fix fido2 Autowired issue

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/UserDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
> Adding tenant domain to the get association response
> Adding tenant domain to the get association response

- pom.xml
As a part of https://github.com/wso2/product-is/issues/5787 …
> Upgrading jackson-databind and jackson-jaxrs-json-provider version

- pom.xml
As a part of https://github.com/wso2/product-is/issues/6423
> Upgrade jackson-databind version to 2.9.9.3

- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.common/pom.xml
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.common/src/main/java/org/wso2/carbon/identity/api/user/totp/common/TOTPConstants.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/dto/ErrorDTO.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/dto/TOTPResponseDTO.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/dto/TOTPSecretResponseDTO.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/dto/UserRequestDTO.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/factories/MeApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/resources/META-INF/cxf/user-totp-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/resources/totp.yaml
- components/org.wso2.carbon.identity.api.user.totp/pom.xml
- pom.xml
- Resolves wso2/product-is#6390
> REST API for TOTP

- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/approval/v1/core/UserApprovalService.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
Also fix https://github.com/wso2/product-is/issues/6498
> Build redirect URLs relative to the server

- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/resources/authorizedApps.yaml
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApi.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApiService.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ApplicationDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ErrorDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionsDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml
Update descriptions of the attributes and the APIs in the swagger definition.
https://app.swaggerhub.com/apis/pamoda/SessionManagementAPI/v1
> Update descriptions in session API swagger definition

- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/pom.xml
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/src/main/java/org/wso2/carbon/identity/api/user/application/common/ApplicationServiceConstants.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/src/main/java/org/wso2/carbon/identity/api/user/application/common/ApplicationServiceHolder.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/src/main/java/org/wso2/carbon/identity/api/user/application/common/factory/OSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/.openapi-generator-ignore
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/application/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/application/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/application/v1/factories/MeApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/application/v1/model/ApplicationListResponse.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/application/v1/model/ApplicationResponse.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/application/v1/model/Error.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/application/v1/model/Link.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/ApplicationService.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/function/ApplicationBasicInfoToApiModel.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/resources/META-INF/cxf/application-user-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/resources/application.yaml
- components/org.wso2.carbon.identity.api.user.application/pom.xml
- pom.xml
Resolves wso2/product-is#6801
Adds the REST API implementation for applications discoverable for end users.
- Adds API definition for Open API
- Implements API definition
Refer https://github.com/wso2/product-is/issues/6794
https://github.com/wso2/product-is/issues/6807
- Integration tests
https://github.com/wso2/product-is/issues/6808
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
https://github.com/wso2/product-is/issues/6809
https://github.com/wso2/carbon-identity-framework/pull/2520
https://github.com/wso2/product-is/issues/6810
> Implement REST API for applications discoverable for user.

- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/ApplicationService.java
> Add API version to link 'href' URI paths.

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/UserDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
- pom.xml
> - Resolves https://github.com/wso2/product-is/issues/6908.
> - Add attributes: first name, last name and email to the associated user response.
> - https://github.com/wso2-extensions/identity-user-account-association/pull/33
> [User API] Add Required Attributes To Associated User

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
> Fix API Description For Associated User Deletion

- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/function/ApplicationBasicInfoToApiModel.java
- pom.xml
Fixes https://github.com/wso2/product-is/issues/7048
> Fix API changes in application management service

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/factory/RealmServiceOSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/util/UserAssociationServiceHolder.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/META-INF/cxf/user-association-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/core/AuthorizedAppsService.java
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.common/src/main/java/org/wso2/carbon/identity/api/user/challenge/common/ChallengeQuestionServiceHolder.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.common/src/main/java/org/wso2/carbon/identity/api/user/challenge/common/factory/RealmServiceOSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/resources/META-INF/cxf/user-challenge-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.common/pom.xml
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UniqueIdToUser.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UserIdToUser.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UserToUniqueId.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/src/main/java/org/wso2/carbon/identity/api/user/session/common/factory/RealmServiceOSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/src/main/java/org/wso2/carbon/identity/api/user/session/common/util/SessionManagementServiceHolder.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/META-INF/cxf/session-user-v1-cxf.xml
- pom.xml
> Use Unique ID In User REST APIs

- pom.xml
> $subject. This PR fixes the test failures regarding the https://github.com/wso2/identity-api-user/pull/73.
> Fix Integration Test Failures With Kernel Dependency

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UserToUniqueId.java
> Resolves https://github.com/wso2/product-is/issues/7102
Code style fix.
> Remove unused import

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UserToUniqueId.java
> Resolves https://github.com/wso2/product-is/issues/7102
> Add Improved Debug Log

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/IdpDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
- pom.xml
Partly resolves https://github.com/wso2/product-is/issues/7403
> Add idp basic information to GET federated-associations

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
Resolves https://github.com/wso2/product-is/issues/7646 …
> Remove userstore domian from username when setting for the User object.

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Constants.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UniqueIdToUser.java
Resolves https://github.com/wso2/product-is/issues/7722 
Resolves wso2/product-is#7628 
Depends on a kernel release with the improvement done in https://github.com/wso2/carbon-kernel/pull/2609 to function properly.
> Gracefully handle user not exists

- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java
Resolves https://github.com/wso2/product-is/issues/7650
> Update response code to 204 for delete operation in Session Management API

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UniqueIdToUser.java
Update error responses when resolving unique user id.
> Update error responses

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Util.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/UserIdApiServiceImpl.java
- pom.xml
> Use the unique user id for user session APIs

- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/pom.xml
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.application/pom.xml
- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.api.user.approval.common/pom.xml
- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.approval/pom.xml
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.association/pom.xml
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.authorized.apps/pom.xml
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.common/pom.xml
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.challenge/pom.xml
- components/org.wso2.carbon.identity.api.user.common/pom.xml
- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.common/pom.xml
- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.fido2/pom.xml
- components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.api.user.recovery.commons/pom.xml
- components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.recovery/pom.xml
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/pom.xml
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.session/pom.xml
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.common/pom.xml
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.totp/pom.xml
- pom.xml
Upgrade the kernel version and release the minor version
> Upgrade the kernel version and release the minor version

- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/resources/approval.yaml
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/resources/authorizedApps.yaml
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/resources/challenge.yaml
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/resources/totp.yaml
Update approval.yaml, association.yaml, authorizedApps.yaml, challenge.yaml, session.yaml, totp.yaml files with scope and permission required for each API
> Update yaml files with scope and permission required for each API

- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.api.user.challenge.common/src/main/java/org/wso2/carbon/identity/api/user/challenge/common/Constant.java
Define error codes related to challenge answer validation feature.
Related PRs: https://github.com/wso2/carbon-identity-framework/pull/2919
> Error codes for challenge answer validation

- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/ApplicationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
- pom.xml
> Fix : https://github.com/wso2/product-is/issues/8296
> Enabled tenant qualified URLs for User APIs.
> Enable tenant qualified urls for user APIs

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
> Add buildURI method to ContextLoadder

- .gitignore
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/.openapi-generator-ignore
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.api.user.functionality.common/pom.xml
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.api.user.functionality.common/src/main/java/org/wso2/carbon/identity/api/user/functionality/common/Constants.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.api.user.functionality.common/src/main/java/org/wso2/carbon/identity/api/user/functionality/common/UserFunctionalityServiceHolder.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.api.user.functionality.common/src/main/java/org/wso2/carbon/identity/api/user/functionality/common/factory/RealmServiceOSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.api.user.functionality.common/src/main/java/org/wso2/carbon/identity/api/user/functionality/common/factory/UserFunctionalityMgtOSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/UserIdApi.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/UserIdApiService.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/factories/MeApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/factories/UserIdApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/model/Error.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/model/LockStatusResponse.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/model/StatusChangeRequest.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/model/UserStatusChangeRequest.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/core/FunctionalityLockStatusToExternal.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/core/UserFunctionalityService.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/functionality/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/resources/META-INF/cxf/user-functionality-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/resources/functionality.yaml
- components/org.wso2.carbon.identity.api.user.functionality/pom.xml
- pom.xml
Depends on this RP https://github.com/wso2/carbon-identity-framework/pull/3068. once it is merged, need to bump framework version
> Enable/Disable user-functionality mgt rest API

- components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/resources/challenge.yaml
Related to https://github.com/wso2/product-is/issues/9732
> Update challenge.yaml with valid sample values

- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/resources/functionality.yaml
Related to wso2/product-is#7727
Adding permission details to the YAML.
> Updating YAML with permissions and scopes details

- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/resources/functionality.yaml
Updating the yaml with the API description to improve IS docs.
> Updating YAML with the description

- components/org.wso2.carbon.identity.api.user.functionality/org.wso2.carbon.identity.rest.api.user.functionality.v1/src/main/resources/functionality.yaml
Organize the operations under 'me' tag and 'admin' tag to improve the docs
> Update yaml with proper tags

- components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/resources/approval.yaml
- Sync with duplicated yaml in docs repo
> remove gender-bias terms for doc purposes

- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml
Fix the test failure by fixing the formatting issue introduced by [1]
[1] https://github.com/wso2/identity-api-user/pull/120
> …
> Fix formatting issue

- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.common/src/main/java/org/wso2/carbon/identity/api/user/totp/common/TOTPConstants.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java
Block TOTP API endpoint for the requests with BasicAuth
> Block TOTP API endpoint for the requests with BasicAuth

- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.common/src/main/java/org/wso2/carbon/identity/api/user/fido2/common/Constants.java
- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/fido2/v1/impl/MeApiServiceImpl.java
Block FIDO2 API endpoint for the requests with BasicAuth
> Block FIDO2 API endpoint for the requests with BasicAuth

- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.common/src/main/java/org/wso2/carbon/identity/api/user/fido2/common/Constants.java
- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/fido2/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/src/main/java/org/wso2/carbon/identity/api/user/session/common/constant/SessionManagementConstants.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.common/src/main/java/org/wso2/carbon/identity/api/user/totp/common/TOTPConstants.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java
- pom.xml
> Add update fixes to 1.1.x

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Util.java
Remove Log4j 1 dependency
Related issue:- https://github.com/wso2/product-is/issues/13042
> Upgrade log4j1 to log4j2

- pom.xml
Upgrade jackson version to 2.1.3.1 and cxf version to 3.5.0
> Upgrade Jackson and CXF versions

- pom.xml
> upgrade jackson, cxf and spring

- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.common/pom.xml
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.common/src/main/java/org/wso2/carbon/identity/api/user/backupcode/common/BackupCodeConstants.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/dto/BackupCodeResponseDTO.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/dto/ErrorDTO.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/dto/UserRequestDTO.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/factories/MeApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/core/BackupCodeService.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/backupcode/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/main/resources/META-INF/cxf/user-backupcode-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.backupcode/org.wso2.carbon.identity.api.user.backupcode.v1/src/main/resources/backupcode.yaml
- components/org.wso2.carbon.identity.api.user.backupcode/pom.xml
- pom.xml
> APIs work with backup code authenticator
merge https://github.com/wso2-extensions/identity-outbound-auth-backup-code/pull/1 before merging this PR
> APIs for Backup authenticator

- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/SessionsApi.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/SessionsApiService.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApi.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApiService.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ApplicationDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ErrorDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SearchResponseDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionsDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/factories/MeApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/factories/SessionsApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/factories/UserIdApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/function/UserSessionToExternal.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/SessionsApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/META-INF/cxf/session-user-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/test/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/function/ApplicationToExternalTest.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/test/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/function/UserSessionToExternalTest.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/test/resources/testng.xml
- pom.xml
> Includes new features to the session management API as per wso2/product-is#12193 (see Goals for more details).
> Includes new features to the session management API:
> * Search active sessions on the system: includes filtering (by user agent, client IP address and login time among other fields) and pagination capabilities.
> * Retrieve a specific session for a certain user.
> https://app.swaggerhub.com/apis/jcgarciaa/wso2is-user-session-management-api/v1
> New endpoint `/{user-id}/sessions/{session-id}`
> Operation available for privileged users, to be invoked on behalf of another user. Retrieves information related to the active session identified by `session-id` of a user identified by `user-id`.
> New endpoint `/sessions`
> Operation available for privileged users. Retrieves …
> Session Management API enhancements

- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionDTO.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/function/UserSessionToExternal.java
- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml
- pom.xml
We are adding `idpName` to the GET endpoints of sessions API to accommodate changes in [this PR](https://github.com/wso2/carbon-identity-framework/pull/4185).
- https://github.com/wso2/product-is/issues/12169
> Link(s) to product documentation that addresses the changes of this PR. If …
> Add idpName to the GET session API response

- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/totp/v1/dto/UserRequestDTO.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/impl/MeApiServiceImpl.java
> Decoupling view and init of TOTP

- pom.xml
> Upgrade Spring to 5.3.25

- components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.common/pom.xml
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.common/src/main/java/org/wso2/carbon/identity/api/user/idv/common/Constants.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.common/src/main/java/org/wso2/carbon/identity/api/user/idv/common/IdentityVerificationServiceHolder.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.common/src/main/java/org/wso2/carbon/identity/api/user/idv/common/factory/IdentityVerificationManagerOSGIFactory.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/DefaultApi.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/DefaultApiService.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/factories/DefaultApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/factories/MeApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/model/Error.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/model/ProviderProperty.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/model/VerificationClaimRequest.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/model/VerificationClaimResponse.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/model/VerificationClaimUpdateRequest.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/model/VerificationPostResponse.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/model/VerifyRequest.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/core/IdentityVerificationService.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/impl/DefaultApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/resources/META-INF/cxf/idv-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/resources/idv.yaml
- components/org.wso2.carbon.identity.api.user.idv/pom.xml
- pom.xml
Identity Verification API Implementation
Related PR: https://github.com/wso2-extensions/identity-verification/pull/1
Epic: https://github.com/wso2-enterprise/iam-engineering/issues/363
> Identity Verification API Implementation

- pom.xml
> Bump identity verification version

- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/idv/v1/DefaultApi.java
$Subject
Related PR: https://github.com/wso2/identity-api-user/pull/168
> Update paths of DefaultAPI

- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/core/IdentityVerificationService.java
Handle Identity Verification Client Exceptions without error logs
> Handle Identity Verification Client Exceptions without error logs

- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/ApplicationService.java
Due to the existing filter argument resolving logic, filter strings with spaces will be treated as invalid queries and hence will not be able to filter apps by such names.
This PR fixes it by resolving the filter argument by parsing it to a `FilterTreeBuilder` and retrieving the filter string.
- https://github.com/wso2/product-is/issues/16274
> Brief description of the …
> Fix application filtering with spaces for user api

- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.api.user.organization.common/pom.xml
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.api.user.organization.common/src/main/java/org/wso2/carbon/identity/api/user/organization/common/UserOrganizationServiceHolder.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.api.user.organization.common/src/main/java/org/wso2/carbon/identity/api/user/organization/common/factory/OrganizationManagementOSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.api.user.organization.common/src/main/java/org/wso2/carbon/identity/api/user/organization/common/factory/OrganizationUserResidentResolverOSGIServiceFactory.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/RootApi.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/RootApiService.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/factories/RootApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/BasicOrganizationObject.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/Error.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/RootOrganizationResponse.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/core/UserOrganizationService.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/exceptions/UserOrganizationManagementEndpointException.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/impl/RootApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/util/Util.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/resources/META-INF/cxf/user-organization-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/resources/user.organization.yaml
- components/org.wso2.carbon.identity.api.user.organization/pom.xml
- pom.xml
> $subject
- https://github.com/wso2/product-is/issues/16359
> Add user organization API

- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/pom.xml
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/MeApi.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/MeApiService.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/factories/MeApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/Link.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/Organization.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/OrganizationsResponse.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/Constants.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/core/UserOrganizationService.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/impl/MeApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/util/Util.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/resources/META-INF/cxf/user-organization-v1-cxf.xml
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/resources/user.organization.yaml
With this new endpoint, users can retrieve organizations in the hierarchy that they are authorized to access.
> Add API to retrieve authorized organizations of user

- components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v2/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v2/impl/core/utils/RecoveryUtil.java
$subject
Related issues: 
- https://github.com/wso2/product-is/issues/16536
- https://github.com/wso2-enterprise/asgardeo-product/issues/19204
> Handle error scenarios related to recovery flow id

- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/core/UserOrganizationService.java
> Fix organization ID set as SUPER org issue

- components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java
- pom.xml
> 
- https://github.com/wso2/product-is/issues/17744
> Fix active user sessions not retrieved for b2b users accessing MyAccount

- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/core/UserOrganizationService.java
> Improve get user authorized organization endpoint
- https://github.com/wso2/product-is/issues/19118
> Improve get user authorized organization endpoint

- pom.xml
> bump jackson dependencies to 2.16.1

- pom.xml
Related to https://github.com/wso2/product-is/issues/19928
Porting the fix done via https://github.com/wso2/identity-api-server/pull/596
> Pin the findsecbugs version

- pom.xml
$subject 
Related issue: https://github.com/wso2/product-is/issues/21200 …
> Upgrade framework and OAuth version

- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.common/pom.xml
- components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/pom.xml
$subject.
Related issue: https://github.com/wso2/product-is/issues/21200 …
> Exclude commons-collection dependency

- pom.xml
> This PR removes dependencies and usages of the Spring framework in the project root pom.xml.
- https://github.com/wso2/product-is/issues/21159
> [Spring Cleanup] Remove Spring dependencies in the project root pom.xml

- components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/core/IdentityVerificationService.java
- pom.xml
- $Subject
- Resolves the issue : https://github.com/wso2/product-is/issues/22120
- To be merged after : https://github.com/wso2-extensions/identity-verification/pull/25
> Update the API response for the IDV claims update related API.

- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.common/pom.xml
- components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.v1/pom.xml
> This PR removes dependencies of the Spring framework in fido component.
- https://github.com/wso2/product-is/issues/21159
> [Spring Cleanup] Remove Spring dependency from fido pom.xml

- pom.xml
> [Spring Cleanup] Remove Spring Dependency from root pom file

- components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v2/src/gen/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v2/AuthorizedAppsApi.java
> Fix AuthorizedAppsApi constructor

- components/org.wso2.carbon.identity.api.user.push/org.wso2.carbon.identity.rest.api.user.push.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/push/v1/impl/DevicesApiServiceImpl.java
> Fix NullPointerException in push device register endpoint

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
> Update user association yaml to reflect the exact responses of the API
https://github.com/wso2/product-is/issues/22678
> Update user association API

- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/RootApi.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/BasicOrganizationObject.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/Organization.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/model/RootOrganizationResponse.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/core/UserOrganizationService.java
- components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/resources/user.organization.yaml
- pom.xml
$subject
**MERGE AFTER:** https://github.com/wso2/identity-api-user/pull/261
**Merge in order:**
- https://github.com/wso2/identity-organization-management-core/pull/172
- https://github.com/wso2/carbon-commons/pull/513
- https://github.com/wso2/carbon-kernel/pull/4276
- https://github.com/wso2-extensions/identity-organization-management/pull/500
- https://github.com/wso2/carbon-multitenancy/pull/290
- https://github.com/wso2/carbon-identity-framework/pull/6685
- https://github.com/wso2/identity-api-server/pull/862
- https://github.com/wso2/identity-api-user/pull/263
> Introduce Organization Handle to Organization User API

- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/FederatedAssociationsApi.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/FederatedAssociationsApiService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/BulkAssociationOperationResponseDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/BulkAssociationOperationResponseStatusDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/BulkFederatedAssociationOperationDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/BulkFederatedAssociationRequestDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/BulkFederatedAssociationResponseDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/FederatedAssociationRequestDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/UserFederatedAssociationDataDTO.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/factories/FederatedAssociationsApiServiceFactory.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/AssociationEndpointConstants.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/FederatedAssociationsApiServiceImpl.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/model/BulkAssociationPathObject.java
- components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml
- pom.xml
- This PR add the Bulk API support for federated User Association.
- Endpoint: `/api/users/v1/federated-associations/bulk`
https://github.com/wso2/product-is/issues/22365
> Add Federated User Association Bulk API
