components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/AssociationEndpointConstants.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/MeApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
pom.xml

>  Engage base64encoded username as the UserId in association APIs
As part of the feature: https://github.com/wso2/product-is/issues/5889

 Engage base64encoded username as the UserId in association APIs

---

components/org.wso2.carbon.identity.api.user.common/pom.xml
components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Util.java
components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/error/ErrorResponse.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/pom.xml
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/src/main/java/org/wso2/carbon/identity/api/user/session/common/constant/SessionManagementConstants.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/src/main/java/org/wso2/carbon/identity/api/user/session/common/util/SessionManagementUtil.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/pom.xml
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/ApiException.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/ApiResponseMessage.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApi.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApiService.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApi.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApiService.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ApplicationDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ErrorDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionsDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/factories/MeApiServiceFactory.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/factories/UserIdApiServiceFactory.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/function/ApplicationToExternal.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/function/UserSessionToExternal.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/MeApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/UserIdApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/META-INF/cxf/session-user-v1-cxf.xml
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml
components/org.wso2.carbon.identity.api.user.session/pom.xml
pom.xml

This PR will add the session management APIs
- GET  /{user-id}/sessions
- DELETE /{user-id}/sessions
- DELETE /{user-id}/sessions/{session-id}
- GET /me/sessions
- DELETE /me/sessions
- DELETE /me/sessions/{session-id}
Uses the backend functionalities introduced by https://github.com/wso2/carbon-identity-framework/pull/2288

Add Session managament API implementation

---

components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/MeApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml

> Use username when creating the associations instead of using userId.

Use username when creating the associations instead of using userId.

---

components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/function/UserToUniqueId.java

> Resolves https://github.com/wso2/product-is/issues/7102
>  With the Kernel alpha, the secondary user store manager must be resolved first, prior to getting unique id for a given user. This PR fixes that code logic.

Refactor code logic to resolve secondary user store manager

---

components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/resources/application.yaml
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/resources/approval.yaml
components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/resources/authorizedApps.yaml
components/org.wso2.carbon.identity.api.user.fido2/org.wso2.carbon.identity.api.user.fido2.v1/src/main/resources/fido.yaml
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml

Resolving https://github.com/wso2/product-is/issues/6414
Remove message body for 401 and 403 responses in user apis swagger doc. Please note that each commit is for each yaml file in api server. In each yaml file schema and content(body) deleted for both responses. Need to update the doc.

Remove message body for 401 and 403 responses in user apis swagger doc

---

components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v1/impl/core/PasswordRecoveryService.java
components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v1/impl/core/UsernameRecoveryService.java
components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v1/impl/core/utils/RecoveryUtil.java

> Fix : https://github.com/wso2/product-is/issues/8296
> Enabled tenant qualified URLs for recovery APIs in user APIs.

Enable tenant qualified urls for recovery API responses

---

components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v1/impl/core/PasswordRecoveryService.java
pom.xml

PR [1] adds an improvement to not to display question based recovery option in the initiate password recovery API response when answers are not set for min. of questions that are required for recovery. This PR adds this new validation check for constructing the proper response body for initiate password recovery API.
Merge after: https://github.com/wso2-extensions/identity-governance/pull/405
Related issue: https://github.com/wso2/product-is/issues/8905
[1] https://github.com/wso2-extensions/identity-governance/pull/405

Improve initiate password recovery API response for question based recovery when answers not set for min. of questions

---

components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApi.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/MeApiService.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApi.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/UserIdApiService.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ApplicationDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/ErrorDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/session/v1/dto/SessionsDTO.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/function/ApplicationToExternal.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/resources/session.yaml
pom.xml

Part of the fix for wso2/product-is#8387
Return application resource id with the sessions object.
Validated against the following test scenarios.
```
<class name="org.wso2.identity.integration.test.rest.api.user.session.v1.UserSessionTest"/>
<class name="org.wso2.identity.integration.test.rest.api.user.session.v1.UserSessionMeSuccessTest"/>
```

Return application resource id with the sessions object

---

components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml

Part of the fix for https://github.com/wso2/product-is/issues/9851
In the API definition, we have used the following as the input request.
```
{
"userId": "john",
"password": "userpassword",
"properties": [
{
"key": "test-key",
"value": "test-value"
}
]
}
```
In the core implementation, we have not used properties attributes. Therefore, the request is misleading. This can be resolved by adding an example.
```
{
"userId": "john",
"password": "userpassword"
}

Add a sample for user association request

---

components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.common/src/main/java/org/wso2/carbon/identity/api/user/session/common/constant/SessionManagementConstants.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java
pom.xml

Related Issues: https://github.com/wso2/product-is/issues/12730
> Currently session reading and deletion using me endpoint does not work for federated users. So federated users cannot terminate their sessions and bonded tokens using the me endpoint. This fix is to enable session delete/terminate for federated users
> Currently when invoking me endpoint, we are checking the userId of the user in userstores. But since federated users are stored in idn databases, We get the userid of federated users from the idn database. After the correct userId is provided, session read/delete work normally.

Enable session read/delete for federated users using me endpoint

---

pom.xml

Upgraded Jackson version to 2.13.0 and CXF version to 3.4.5 to mitigate the known vulnerabilities.

Upgrade Jackson and CXF versions

---

components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java

Resolves https://github.com/wso2/product-is/issues/13382.
We should not log the errors for client exceptions. 
Before the fix:
We were logging error with exception for client exceptions too.
```
[2022-04-28 10:37:58,489] [c13adb48-6cc7-4386-b938-4b2620443168] ERROR {org.wso2.carbon.identity.rest.api.user.association.v1.core.UserAssociationService} - errorCode: 8526 | message: 8526 - The user name or password you entered is incorrect org.wso2.carbon.identity.user.account.association.exception.UserAccountAssociationClientException: 8526 - The user name or password you entered is incorrect
at org.wso2.carbon.identity.user.account.association.UserAccountConnectorImpl.handleUserAccountAssociationClientException(UserAccountConnectorImpl.java:500)
at …
```

Stop printing error logs for client exceptions in user account association flow and make it debug logs

---

pom.xml

This PR will
- update the maven-compiler-plugin version to the latest (3.10.1)
- Set the <parameters> configuration of maven-compiler-plugin to true
https://github.com/wso2/product-is/issues/14129
https://github.com/wso2/identity-api-server/pull/375
In MyAccount, go to `Security > Additional Authentication > Authenticator App`.
Click on the `+` sign to add an Authenticator app.
With this fix, the following WARN log should **not** be generated.
```
[2022-07-11 15:37:45,880] [4ddac944-b65d-4a96-938f-c6ea08a25db4]  WARN {org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable} - HV000254: Missing parameter metadata for ActionEnum(String, int), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield …
```

Update maven-compiler-plugin version and set parameters to true

---

components/org.wso2.carbon.identity.api.user.mfa/org.wso2.carbon.identity.api.user.mfa.common/src/main/java/org/wso2/carbon/identity/api/user/mfa/common/MFAConstants.java

With the fix for https://github.com/wso2/product-is/issues/14843, we'll be introducing a new parameter to resolve the authenticator identifier in `authenticationOptions`. For backup code feature, ideally we should use authenticator name to resolve the `authenticationOptions` in mfa flow.
Details: https://github.com/wso2/product-is/issues/14843#issuecomment-1236530106
- https://github.com/wso2/product-is/issues/14844
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? …

Use authenticator name when validating backup code feature related authenticators

---

components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java
pom.xml

Resolves: https://github.com/wso2/product-is/issues/15197
With this fix, "http://wso2.org/claims/identity/verifySecretkey" claim will be used to store the secret key temporarily before validating it. After the secret key is validated it will move to "http://wso2.org/claims/identity/secretkey".
Related PR: https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/147

Validate totp secret key before storing

---

components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/core/IdentityVerificationService.java
components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/impl/DefaultApiServiceImpl.java
pom.xml

$Subject
Related PR: https://github.com/wso2-extensions/identity-verification/pull/8

Bump the version and update getIdVClaims method

---

components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v1/impl/core/utils/RecoveryUtil.java
pom.xml

Due to the encountered issues with the current V1 API, a new V2 API is provided. Hence, current recovery service will be disabled. There will be a config to enable/disable the service. This PR handles the client exception when the recovery service is disabled.
Related issue: https://github.com/wso2/product-is/issues/16536
This should be merged after https://github.com/wso2-extensions/identity-governance/pull/766
Governance version: v1.8.73

Handle client exception when API is disabled

---

components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/ApplicationService.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/MeApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v1/impl/UserIdApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v2/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v2/core/AuthorizedAppsService.java
components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v2/src/main/java/org/wso2/carbon/identity/rest/api/user/authorized/apps/v2/impl/UserIdApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/core/UserChallengeService.java
components/org.wso2.carbon.identity.api.user.challenge/org.wso2.carbon.identity.rest.api.user.challenge.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/challenge/v1/impl/UserIdApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/idv/v1/core/IdentityVerificationService.java
components/org.wso2.carbon.identity.api.user.mfa/org.wso2.carbon.identity.api.user.mfa.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/mfa/v1/core/MFAService.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/SessionsApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/UserIdApiServiceImpl.java
pom.xml

Related issue:
- https://github.com/wso2/product-is/issues/16906
Improve resolving tenant domain when tenant qualified URL feature is enabled. If the tenant domain is available in the context retrieve it otherwise retrieve tenant domain from the privileged carbon context.

Improve tenant resolving with tenant qualified URL enabled

---

components/org.wso2.carbon.identity.api.user.common/pom.xml
components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Constants.java
components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/pom.xml
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/core/UserOrganizationService.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/util/Util.java
pom.xml

> $subject
- https://github.com/wso2/product-is/issues/17606

Improve organization perspective service URL build

---

components/org.wso2.carbon.identity.api.user.common/pom.xml
components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/Constants.java
components/org.wso2.carbon.identity.api.user.common/src/main/java/org/wso2/carbon/identity/api/user/common/ContextLoader.java

> 
- https://github.com/wso2/carbon-identity-framework/pull/5148
- https://github.com/wso2/product-is/issues/17606

Remove the obsolete logic of building organization perspective service URLs

---

components/org.wso2.carbon.identity.api.user.onboard/org.wso2.carbon.identity.api.user.onboard.v1/src/main/java/org/wso2/carbon/identity/api/user/onboard/v1/service/OfflineInviteLinkService.java

Resolve the tenant domain from the PrivilegedCarbonContext rather than the auth_user since the auth user is a shadow account of a root org user for subOrgs.
Issue : https://github.com/wso2/product-is/issues/18788

Resolve tenant domain from PrivilegedCarbonContext

---

components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.api.user.organization.common/pom.xml
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.api.user.organization.common/src/main/java/org/wso2/carbon/identity/api/user/organization/common/UserOrganizationServiceHolder.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.api.user.organization.common/src/main/java/org/wso2/carbon/identity/api/user/organization/common/factory/ApplicationManagementOSGIServiceFactory.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/pom.xml
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/MeApi.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/organization/v1/MeApiService.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/core/UserOrganizationService.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/organization/v1/impl/MeApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/resources/META-INF/cxf/user-organization-v1-cxf.xml
components/org.wso2.carbon.identity.api.user.organization/org.wso2.carbon.identity.rest.api.user.organization.v1/src/main/resources/user.organization.yaml
pom.xml

- Improve get user authorized organization endpoint
- At the moment, we identify a given organization is an authorized organization if a user association with the authenticated user for that given organization exist. We can improve that logic further to check the associated user has a role associated with him to indicate it is an authorized organization.
- https://github.com/wso2/product-is/issues/18727
- https://github.com/wso2/identity-organization-management-core/pull/123

Improve get user authorized organization endpoint

---

components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java

- $Subject
- https://github.com/wso2/product-is/issues/18543

Enforce the Usage of `verifySecretKey` Claim when Generating TOTP Secret Keys Using `me/totp/secret` GET Endpoint

---

components/org.wso2.carbon.identity.api.user.onboard/org.wso2.carbon.identity.api.user.onboard.common/src/main/java/org/wso2/carbon/identity/api/user/onboard/common/error/ErrorResponse.java

Client errors should not be logged on the server side. This PR fixes instances where client errors are logged in the  offline invite link flow
- https://github.com/wso2/product-is/issues/19456

Fix issue with logging client errors in offline invite link flow

---

components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/core/SessionManagementService.java

> Organization SSO users are federated users but not required to handles as federated users when resolving user information (ex: user-id , username). Treating as local user id/username resolving will resolve the issue.
Though we have handled the organization SSO as federated flow, there is a POC going on to handled as local users, which will be align with the assumption made here.
- https://github.com/wso2/product-is/issues/20576

Fix session revocation issue for the sub-organization users

---

components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/pom.xml
components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/src/main/java/org/wso2/carbon/identity/api/user/application/common/ApplicationServiceHolder.java
components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.api.user.application.common/src/main/java/org/wso2/carbon/identity/api/user/application/common/factory/OrganizationManagementOSGIServiceFactory.java
components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/pom.xml
components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/ApplicationService.java
components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/resources/META-INF/cxf/application-user-v1-cxf.xml
pom.xml

> $subject
Related PR: https://github.com/wso2-extensions/identity-organization-management/pull/390
Related issue: https://github.com/wso2/product-is/issues/21118
Merge after: https://github.com/wso2-extensions/identity-organization-management/pull/392
> Link(s) to product …

Retrieve Discoverable Applications for Sub-Org from the Organization Application Management Service

---

README.md

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject as travis ci is no longer being used

Remove travis CI status from README

---

components/org.wso2.carbon.identity.api.user.common/pom.xml

> Remove spring dependency from user common component.
NOTE: The spring dependency has not been utilized in user common component even though the dependency has been added.
- https://github.com/wso2/product-is/issues/21159

[Spring Cleanup] Remove Spring dependency from user common component

---

components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.api.user.recovery.commons/src/main/java/org/wso2/carbon/identity/api/user/recovery/commons/UserAccountRecoveryServiceDataHolder.java
components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.api.user.recovery.commons/src/main/java/org/wso2/carbon/identity/api/user/recovery/commons/factory/PasswordRecoveryManagerOSGIServiceFactory.java
components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v2/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v2/impl/core/PasswordRecoveryService.java

The previous data holder could keep one PasswordRecoveryManager implementation at once. But there can be multiple implementations, hence it should be a list, and the API should response with respect to all the available PasswordRecoveryManager implementations in order to proceed for the next steps of the password recovery via the API.
- https://github.com/wso2/product-is/issues/21106

Retrieve all the registered password recovery managers

---

components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/UserIdApi.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/UserIdApiService.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/association/v1/dto/FederatedAssociationRequestDTO.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/core/UserAssociationService.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/association/v1/impl/UserIdApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.association/org.wso2.carbon.identity.api.user.association.v1/src/main/resources/association.yaml

> $subject
https://github.com/wso2/product-is/issues/22282

Add federated user account link API

---

components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v2/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v2/impl/core/Constants.java
components/org.wso2.carbon.identity.api.user.recovery/org.wso2.carbon.identity.rest.api.user.recovery.v2/src/main/java/org/wso2/carbon/identity/rest/api/user/recovery/v2/impl/core/utils/RecoveryUtil.java

> This PR may resolve https://github.com/wso2/product-is/issues/21659
> This PR ensures that a 400 status code is returned instead of a 500 when the API endpoint /recovery/password/recover encounters an invalid channel ID in the request body during account recovery v2.
**Behavior After Fix:**
> Below is the Sample Request & response.
> **Request [Recover Password with invalid channel Id]**
```
curl --location 'https://localhost:9443/api/users/v2/recovery/password/recover' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic <base64 username:password>' \
--data '{
"recoveryCode": "<recovery-code>",
"channelId": "<invalid-channel-id>"
}'
```
> **Response [Recover Password with invalid channel Id]**
Response Code - 400
```
{
"code": "UAR-10004",
"message": "Bad …
```

Fix for issue product-is/21659

---

.github/workflows/pr-builder.yml

Bump actions/cache version since v2 is deprecated.
- https://github.com/wso2/product-is/issues/23500

Update pr-builder.yml bump actions/cache version

---

components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.api.user.approval.common/pom.xml
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.api.user.approval.common/src/main/java/org/wso2/carbon/identity/api/user/approval/common/ApprovalConstant.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/pom.xml
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/MeApi.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/MeApiService.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/dto/ErrorDTO.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/dto/PropertyDTO.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/dto/StateDTO.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/dto/TaskDataDTO.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/dto/TaskSummaryDTO.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/factories/MeApiServiceFactory.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/model/Error.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/model/Property.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/model/State.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/model/StateDTO.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/model/TaskData.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/gen/java/org/wso2/carbon/identity/rest/api/user/approval/v1/model/TaskSummary.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/approval/v1/core/factories/ApprovalEventServiceFactory.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/approval/v1/impl/MeApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/resources/approval.yaml
components/org.wso2.carbon.identity.api.user.approval/pom.xml
pom.xml

> Add user approval APIs to facilitate approval-based workflows. Resolves issue: https://github.com/wso2/product-is/issues/23374
- Provide a set of APIs to manage approval tasks related to user actions.
- Allow relevant parties to retrieve, approve, reject, and track approval requests.
- Allow integration with simple workflow engine instead of BPS engine.
**User Approval API Specification**
> https://app.swaggerhub.com/apis/SenuriMallikarachchi/User-Approvals/1.0.0
> Link to the PR for changes to …

Add User Approval APIs

---

components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/MeApiServiceImpl.java
components/org.wso2.carbon.identity.api.user.session/org.wso2.carbon.identity.api.user.session.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/session/v1/impl/UserIdApiServiceImpl.java
pom.xml

- Set the Flow values for the User Session Termination workflows.
- This is needed for CAEP and WSO2 Eventing Profiles.
- When a termination event is received, the IdentityContext Flow value will be set to SESSION_REVOKE and InitiatingPersona will be set to either ADMIN or USER depending on the flow.
- A new private function will be called in user session termination flows, which sets the IdentityContext ThreadLocalIdentityContext.
- https://github.com/wso2/product-is/issues/24072

Set flows for session termination

---

components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java
pom.xml

As the authenticated user is required to obtain and update some claims, it is being passed alongwith to the TOTP verification. 
Issue : https://github.com/wso2/product-is/issues/25205

Provide Authenticated User to Verify TOTP Code

---

components/org.wso2.carbon.identity.api.user.approval/org.wso2.carbon.identity.rest.api.user.approval.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/approval/v1/impl/MeApiServiceImpl.java

$subject
This pull request improves error handling in the `MeApiServiceImpl` class for the user approval API. The main change is to provide a clear error response when a requested approval task does not exist, instead of returning a null or empty response.
**Error handling improvements:**
* Added a check in `getApprovalTaskInfo` to return a `404 NOT FOUND` error with a descriptive message if the approval task with the given `taskId` does not exist, using the `APIError` and `ErrorResponse` classes.
**Dependency and import updates:**
* Imported `ApprovalConstant`, `APIError`, and `ErrorResponse` to support the new error handling logic.
- https://github.com/wso2/product-is/issues/25907
- https://github.com/wso2-extensions/identity-workflow/pull/28

Return NOT_FOUND response when approval not found.
